---

- name: docker
  image: dropveter/docker-dind-ansible:latest
  privileged: true
  pre_build_image: false
  environment:
    DOCKER_TLS_CERTDIR: /certs
  volumes:
    - certs-ca
    - certs-client
  networks:
    - network
