---

- name: Restart docker
  community.docker.docker_compose_v2:
    state: present
    project_src: "{{ wordpress_docker_data }}"
    build: never
    pull: missing

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
